#!/usr/bin/env python3
"""Generate dos/VLAKDATA.C from the upstream sources.

Bulk tables are sliced from a VLAK.COM assembled from pristine upstream
sources (build/pristine, see tools/dos_runner.py); graphics are concatenated
from the .SCR files in exactly the order used by upstream A.BAT and the
RUZNE/VAGONY/VECI batch files.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "reference/upstream/SRC"
PRISTINE = ROOT / "build/pristine"
OUT = ROOT / "dos/VLAKDATA.C"


def listing_offsets(lst: Path) -> dict[str, int]:
    offsets: dict[str, int] = {}
    pat = re.compile(r"^\s*\d+\s+([0-9A-F]{4})\s+(?:\S.*?\s)?\s*([A-Za-z]\w*)\s+(db|dw|label)\b")
    for line in lst.read_text(encoding="latin-1").splitlines():
        m = pat.match(line)
        if m:
            offsets.setdefault(m.group(2), int(m.group(1), 16))
    return offsets


def batch_order(bat: Path) -> list[str]:
    """Return the component file names in concatenation order of a *.BAT."""
    names: list[str] = []
    for line in bat.read_text(encoding="latin-1").splitlines():
        m = re.match(r"(?i)\s*copy\s+/b\s+(\S+)", line)
        if not m:
            continue
        for part in m.group(1).split("+"):
            if not re.match(r"(?i)(ruzne|vagony|veci)\d\d\.scr$", part):
                names.append(part.upper())
    return names


def images() -> bytes:
    blob = (SRC / "NIC.SCR").read_bytes()
    for group in ("RUZNE", "VAGONY", "VECI"):
        for name in batch_order(SRC / f"{group}.BAT"):
            path = SRC / group / name
            data = path.read_bytes()
            if len(data) != 128:
                raise ValueError(f"{path} has {len(data)} bytes")
            blob += data
    return blob


def c_array(name: str, data: bytes, qual: str = "") -> str:
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ",".join(f"0x{b:02X}" for b in data[i:i + 16]))
    return f"{qual}unsigned char {name}[{len(data)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def main() -> int:
    com = (PRISTINE / "VLAK.COM").read_bytes()
    off = listing_offsets(PRISTINE / "VLAK.LST")
    base = 0x100

    def mem(start: int, length: int) -> bytes:
        return com[start - base:start - base + length]

    sceny = mem(off["Sceny"], off["TabHesel"] - off["Sceny"])
    hesla = mem(off["TabHesel"], off["Titulek"] - off["TabHesel"])
    uv = mem(off["UvTxt"], off["BuffHes"] - off["UvTxt"])
    card = mem(off["CardTxt"], off["UvTxt"] - off["CardTxt"])
    noise = mem(base, 122)  # words at Start+1 .. Start+120 (crash sound)
    assert len(sceny) == 52 * 240 and len(hesla) == 51 * 5
    assert uv.endswith(b"$") and card.endswith(b"$")
    assert off["Pole"] + 240 == off["AktScen"] and off["AktScen"] + 1 == off["Sceny"]
    assert off["TabSLok"] + 6 == off["TabSVec"] and off["TabSVec"] + 36 == off["Smer"]

    title = (SRC / "TITULEK.SCR").read_bytes()
    img = images()
    assert len(title) == 2048 and len(img) == 156 * 128

    text = [
        "/* Generated by tools/gen_dos_data.py from reference/upstream; do not edit. */\n",
        '#include "VLAK.H"\n\n',
        "/* Pole, AktScen and Sceny are contiguous in the original data segment. */\n",
        "unsigned char Mem[MEM_SIZE] = {\n    " + ",".join(["0"] * 240) + ",\n    1,\n",
    ]
    rows = [",".join(f"0x{b:02X}" for b in sceny[i:i + 16]) for i in range(0, len(sceny), 16)]
    text.append("    " + ",\n    ".join(rows) + "\n};\n\n")
    text.append(c_array("TabHesel", hesla))
    text.append(c_array("UvTxt", uv))
    text.append(c_array("CardTxt", card))
    text.append(c_array("StartCode", noise))
    text.append(c_array("Titulek", title))
    text.append(c_array("Obrazky", img))
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(text), encoding="ascii", newline="\r\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
